# Generated by Django 4.2 on 2023-04-17 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_price_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='price',
        ),
    ]
